# tomcat
server:
  port: 28083
# springboot
spring:
  profiles:
    active: dev
  datasource:
    name: my-blog-datasource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${mysql.host}:${mysql.port}/${mysql.database}?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&serverTimezone=UTC
    username: ${mysql.username}
    password: ${mysql.password}
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 20000
      pool-name: hikariCP
      max-lifetime: 30000
      connection-timeout: 30000
      connection-test-query: SELECT 1
# mybatis-plus
mybatis-plus:
  type-aliases-package: com.site.blog.my.core.pojo.po
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: is_deleted
      logic-not-delete-value: 0
      logic-delete-value: 1